### ISSUE TITLE
Dolphin removed support for DVD backups

### ISSUE THREAD

**Issue by SNBeast** [LMauricius/EmuDiscer#2]
https://github.com/dolphin-emu/dolphin/pull/11456

**Comment by LMauricius** [comment]
Well there goes Dolphin. I don't get why anyone would be against people using dvds, not like they forced to.

Edit: it might be possible to emulate an iso from the dvd drive using just system features, but I'm not able to work on this anytime soon. EmuDiscer can be considered a work in progress though, it isn't abandoned.

**Comment by LPFan12** [comment]
Technically a viable alternative would be to fork Dolphin to add the feature back and add a * to the support of this to clarify that it is only compatible with the custom branch. It would cause inconvinience for the user-side, but it would be a better solution than dropping the support entirely and confusion would be minimal, considering everyone who gets here in the first place should be able to notice the references to the alternate version of Dolphin.

**Comment by LMauricius** [comment]
> Technically a viable alternative would be to fork Dolphin to add the feature back and add a * to the support of this to clarify that it is only compatible with the custom branch. It would cause inconvinience for the user-side, but it would be a better solution than dropping the support entirely and confusion would be minimal, considering everyone who gets here in the first place should be able to notice the references to the alternate version of Dolphin. 

I was thinking about that. Although maybe someone could one day fix the disk loading in a more maintanable way and put it back into the og Dolphin. DVDs will probably become more popular in a decade or two again, just like vynil did.
